allow_remote_control yes

enable_keyboard_protocol no

enabled_layouts splits,stack

# Panel/window navigation (avoid [ ] key layout issues)
map cmd+alt+left neighboring_window left
map cmd+alt+right neighboring_window right
map cmd+alt+down neighboring_window down
map cmd+alt+up neighboring_window up
map cmd+alt+equal launch --location=split --cwd=current
map cmd+alt+minus launch --location=hsplit --cwd=current
map cmd+alt+backslash launch --location=vsplit --cwd=current
map cmd+alt+shift+equal remote_control_script /Users/zhiqiang/Code/dotfiles/bin/kitty-remote-fork window
map cmd+alt+backspace close_window
map cmd+alt+enter toggle_layout stack
map cmd+alt+shift+enter remote_control_script /Users/zhiqiang/Code/dotfiles/bin/kitty-remote-fork vsplit
map cmd+alt+shift+minus remote_control_script /Users/zhiqiang/Code/dotfiles/bin/kitty-remote-fork hsplit
map cmd+enter toggle_fullscreen
map cmd+r send_text normal,application \x0c

# Tab management
map cmd+t new_tab
map cmd+left previous_tab
map cmd+right next_tab

# Shell/input editing
map alt+left send_text normal,application \x1bb
map alt+right send_text normal,application \x1bf

# Make focused window border more obvious
window_border_width 3px
